# Generated by Django 3.2.4 on 2021-07-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0002_artist_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='rating',
            field=models.FloatField(default=3),
        ),
    ]
